### ISSUE TITLE
big emotes

### ISSUE THREAD

**Issue by sadbear-** [Noitamin/zooeybot#5]
big <emote>

When a user types big <emote>, zoi posts the enlarged version of it. This should recognize both the forms big :emotename: and big emotename, although the latter will only parse default and server emotes.

This can be extended; if super large versions exist of some emotes, then enable a command like "super big emote" to post the enlarged version.

**Comment by Noitamin** [comment]
custom emojis can now be hugified. next step to extract whole image and reply with that instead of using a link.
